namespace AppGen.Core.Themes;

public sealed record MobileThemeDefinition(
    string Id,
    string DisplayName,
    string Description,
    string Sidebar,
    string SidebarAccent,
    string Accent,
    string AccentMuted,
    string Background,
    string Surface,
    string Border,
    string Text,
    string TextMuted,
    string Highlight,
    string Success,
    string Error,
    string? OnAccent = null,
    string? OnSidebar = null,
    string? SidebarSelectedBackground = null,
    string HeadingFont = "inter",
    string BodyFont = "inter",
    string ButtonFont = "inter",
    double CornerRadius = 8,
    bool IsDark = false,
    double MinButtonHeight = 44,
    bool UsesDashboardNav = false,
    bool HideWhenDocumentationDisabled = false);
