using AppGen.Core.Models;

namespace AppGen.Engine;

internal static class GenerationCopyHelper
{
    public static string ResolveTagline(SolutionSpec spec)
    {
        if (!string.IsNullOrWhiteSpace(spec.Project?.Tagline))
            return spec.Project.Tagline.Trim();

        if (!string.IsNullOrWhiteSpace(spec.Portal?.Settings.Tagline))
            return spec.Portal.Settings.Tagline!.Trim();

        return "Generated by AppGen";
    }

    public static string ResolveEntityDescription(SolutionSpec spec, string entityName)
    {
        var sketch = spec.EntitySketches.FirstOrDefault(s =>
            s.Name.Equals(entityName, StringComparison.OrdinalIgnoreCase));

        if (!string.IsNullOrWhiteSpace(sketch?.Description))
            return sketch.Description.Trim();

        return $"Browse and manage {entityName} records.";
    }
}
