using System.Text;
using AppGen.Core;
using AppGen.Core.Models;

namespace AppGen.Engine;

public static class OracleScriptGenerator
{
    public static async Task WriteAsync(SolutionSpec spec, string outputDirectory, CancellationToken ct = default)
    {
        if (spec.Database != DatabaseProvider.Oracle || spec.Entities.Count == 0)
            return;

        var schemaPrefix = spec.Setup.OracleSchemaPrefix ?? "SE";
        var scriptDir = Path.Combine(outputDirectory, "scripts", "oracle");
        Directory.CreateDirectory(scriptDir);

        var create = BuildCreateScript(spec, schemaPrefix);
        await File.WriteAllTextAsync(Path.Combine(scriptDir, "001-create-tables.sql"), create, ct);

        var seed = BuildSeedScript(spec, schemaPrefix);
        await File.WriteAllTextAsync(Path.Combine(scriptDir, "002-seed-data.sql"), seed, ct);
    }

    private static string BuildCreateScript(SolutionSpec spec, string schemaPrefix)
    {
        var schema = NamingHelper.ToOracleSchema(schemaPrefix);
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by AppGen. Run against your Oracle schema before or instead of EnsureCreated.");
        sb.AppendLine($"-- Table pattern: {schema}.{schema}_<ENTITY>");
        sb.AppendLine();

        foreach (var entity in spec.Entities)
        {
            var qualified = NamingHelper.ToOracleTableName(schemaPrefix, entity.Name);
            var tableOnly = NamingHelper.ToOracleTableNameOnly(schemaPrefix, entity.Name);
            var props = EntityGenerator.ExpandEntityProperties(entity);

            sb.AppendLine($"-- {entity.Name}");
            sb.AppendLine($"CREATE TABLE {qualified} (");
            var columns = props.Select(p =>
                $"    {ToOracleColumn(p.Name)} {MapOracleType(p)}{(p.IsNullable ? "" : " NOT NULL")}");
            sb.AppendLine(string.Join($",{Environment.NewLine}", columns));

            var key = EntityGenerator.ExpandEntityProperties(entity).First(p => p.IsKey);
            sb.AppendLine($",    CONSTRAINT PK_{tableOnly} PRIMARY KEY ({ToOracleColumn(key.Name)})");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        foreach (var entity in spec.Entities)
        {
            foreach (var prop in EntityGenerator.ExpandEntityProperties(entity).Where(p => !p.IsKey && !string.IsNullOrWhiteSpace(p.ForeignKeyEntity)))
            {
                var refEntity = spec.Entities.FirstOrDefault(e =>
                    e.Name.Equals(prop.ForeignKeyEntity, StringComparison.OrdinalIgnoreCase));
                if (refEntity is null) continue;

                var tableOnly = NamingHelper.ToOracleTableNameOnly(schemaPrefix, entity.Name);
                var refTable = NamingHelper.ToOracleTableNameOnly(schemaPrefix, refEntity.Name);
                var refKey = EntityGenerator.ExpandEntityProperties(refEntity).First(p => p.IsKey);
                sb.AppendLine($"ALTER TABLE {NamingHelper.ToOracleTableName(schemaPrefix, entity.Name)}");
                sb.AppendLine($"    ADD CONSTRAINT FK_{tableOnly}_{ToOracleColumn(prop.Name)}");
                sb.AppendLine($"    FOREIGN KEY ({ToOracleColumn(prop.Name)}) REFERENCES {NamingHelper.ToOracleSchema(schemaPrefix)}.{refTable} ({ToOracleColumn(refKey.Name)});");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string BuildSeedScript(SolutionSpec spec, string schemaPrefix)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Simple sample data. Adjust or re-run after clearing tables.");
        sb.AppendLine();

        long id = 1;
        foreach (var entity in spec.Entities)
        {
            var qualified = NamingHelper.ToOracleTableName(schemaPrefix, entity.Name);
            var props = EntityGenerator.ExpandEntityProperties(entity);
            var columns = string.Join(", ", props.Select(p => ToOracleColumn(p.Name)));
            var values = string.Join(", ", props.Select(p => SampleValue(p, ref id)));
            sb.AppendLine($"INSERT INTO {qualified} ({columns}) VALUES ({values});");
            sb.AppendLine("COMMIT;");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string ToOracleColumn(string name) => NamingHelper.ToOracleColumnName(name);

    private static string MapOracleType(PropertySpec p) => p.ClrType switch
    {
        "string" => "VARCHAR2(4000)",
        "int" => "NUMBER(10)",
        "long" => "NUMBER(19)",
        "decimal" or "double" => "NUMBER(18,4)",
        "bool" => "NUMBER(1)",
        "DateTime" => "TIMESTAMP",
        "Guid" => "RAW(16)",
        _ => "VARCHAR2(4000)"
    };

    private static string SampleValue(PropertySpec p, ref long seedId)
    {
        if (p.IsKey)
            return (seedId++).ToString();

        if (!string.IsNullOrWhiteSpace(p.ForeignKeyEntity))
            return "1";

        return p.ClrType switch
        {
            "string" => $"'Sample {p.Name}'",
            "int" => "1",
            "long" => "1",
            "decimal" or "double" => "0",
            "bool" => "0",
            "DateTime" => "SYSTIMESTAMP",
            "Guid" => "SYS_GUID()",
            _ => "NULL"
        };
    }
}
