using System.Text;
using AppGen.Core.Models;

namespace AppGen.Engine;

public static class PostgreSqlScriptGenerator
{
    public static Task WriteAsync(SolutionSpec spec, string outputDirectory, CancellationToken ct = default) =>
        WriteAsync(spec, outputDirectory, entityData: null, ct);

    public static async Task WriteAsync(
        SolutionSpec spec,
        string outputDirectory,
        IReadOnlyDictionary<string, List<Dictionary<string, string>>>? entityData,
        CancellationToken ct = default)
    {
        if (spec.Database != DatabaseProvider.PostgreSql || spec.Entities.Count == 0)
            return;

        var scriptDir = Path.Combine(outputDirectory, "scripts", "postgresql");
        Directory.CreateDirectory(scriptDir);

        await File.WriteAllTextAsync(
            Path.Combine(scriptDir, "001-create-tables.sql"),
            BuildCreateScript(spec),
            ct);

        var seed = entityData is not null
            ? ImportedSeedScriptBuilder.BuildPostgreSql(spec, entityData)
            : BuildSeedScript(spec);

        await File.WriteAllTextAsync(
            Path.Combine(scriptDir, "002-seed-data.sql"),
            seed,
            ct);
    }

    private static string BuildCreateScript(SolutionSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by AppGen. Run against your PostgreSQL database before or instead of EnsureCreated.");
        sb.AppendLine("-- Example: psql -d YourDatabase -f 001-create-tables.sql");
        sb.AppendLine();

        foreach (var entity in spec.Entities)
        {
            var table = QualifiedTable(entity, spec.Database);
            var props = EntityGenerator.ExpandEntityProperties(entity);

            sb.AppendLine($"-- {entity.Name}");
            sb.AppendLine($"CREATE TABLE {table} (");
            var columns = props.Select(p =>
                $"    {Quote(ColumnName(p))} {MapType(p, props)}{(p.IsNullable ? "" : " NOT NULL")}");
            sb.AppendLine(string.Join($",{Environment.NewLine}", columns));

            var key = props.First(p => p.IsKey);
            sb.AppendLine($",    CONSTRAINT {Quote($"PK_{SqlScriptHelpers.TableName(entity)}")} PRIMARY KEY ({Quote(ColumnName(key))})");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        foreach (var entity in spec.Entities)
        {
            foreach (var prop in EntityGenerator.ExpandEntityProperties(entity).Where(p => !p.IsKey))
            {
                var refEntity = SqlScriptHelpers.ResolveForeignKeyEntity(spec, prop);
                if (refEntity is null) continue;

                var tableOnly = SqlScriptHelpers.TableName(entity);
                var refKey = EntityGenerator.ExpandEntityProperties(refEntity).First(p => p.IsKey);
                sb.AppendLine($"ALTER TABLE {QualifiedTable(entity, spec.Database)}");
                sb.AppendLine($"    ADD CONSTRAINT {Quote($"FK_{tableOnly}_{ColumnName(prop)}")}");
                sb.AppendLine($"    FOREIGN KEY ({Quote(ColumnName(prop))}) REFERENCES {QualifiedTable(refEntity, spec.Database)} ({Quote(ColumnName(refKey))});");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string BuildSeedScript(SolutionSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Simple sample data. Adjust or re-run after clearing tables.");
        sb.AppendLine();

        var entitySeedIds = SeedScriptHelpers.AssignEntitySeedIds(spec);
        foreach (var entity in spec.Entities)
        {
            var table = QualifiedTable(entity, spec.Database);
            var props = EntityGenerator.ExpandEntityProperties(entity);
            var columns = string.Join(", ", props.Select(p => Quote(ColumnName(p))));
            var values = string.Join(", ", props.Select(p => SampleValue(entity, p, spec, entitySeedIds)));
            sb.AppendLine($"INSERT INTO {table} ({columns}) VALUES ({values});");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string QualifiedTable(EntitySpec entity, DatabaseProvider database) =>
        $"{Quote(SqlScriptHelpers.SchemaOrDefault(entity, database))}.{Quote(SqlScriptHelpers.TableName(entity))}";

    private static string ColumnName(PropertySpec p) =>
        SqlScriptHelpers.ColumnName(p, DatabaseProvider.PostgreSql);

    private static string Quote(string identifier) =>
        $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";

    private static string MapType(PropertySpec p, IReadOnlyList<PropertySpec> properties)
    {
        var identity = SqlScriptHelpers.IsAutoIncrementKey(properties, p);
        return p.ClrType switch
        {
            "string" => "TEXT",
            "int" => identity ? "INTEGER GENERATED BY DEFAULT AS IDENTITY" : "INTEGER",
            "long" => identity ? "BIGINT GENERATED BY DEFAULT AS IDENTITY" : "BIGINT",
            "decimal" => "NUMERIC(18,4)",
            "double" => "DOUBLE PRECISION",
            "bool" => "BOOLEAN",
            "DateTime" => "TIMESTAMP",
            "Guid" => "UUID",
            _ => "TEXT"
        };
    }

    private static string SampleValue(
        EntitySpec entity,
        PropertySpec p,
        SolutionSpec spec,
        IReadOnlyDictionary<string, long> entitySeedIds)
    {
        if (p.IsKey)
            return SeedScriptHelpers.KeySampleValue(entity, entitySeedIds);

        var fkValue = SeedScriptHelpers.ForeignKeySampleValue(spec, p, entitySeedIds);
        if (fkValue is not null)
            return fkValue;

        return p.ClrType switch
        {
            "string" => $"'{p.Name.Replace("'", "''", StringComparison.Ordinal)} sample'",
            "int" => "1",
            "long" => "1",
            "decimal" or "double" => "0",
            "bool" => "FALSE",
            "DateTime" => "NOW()",
            "Guid" => "gen_random_uuid()",
            _ => "NULL"
        };
    }
}
