using System.Text;

using AppGen.Core;

using AppGen.Core.Models;



namespace AppGen.Engine;



public static class ReadmeGenerator

{

    public static async Task WriteAsync(SolutionSpec spec, string outputDirectory, CancellationToken ct = default)

    {

        var sb = new StringBuilder();

        sb.AppendLine($"# {spec.ApplicationName}");

        sb.AppendLine();

        sb.AppendLine("Generated by AppGen.");

        sb.AppendLine();

        sb.AppendLine("## First run");

        sb.AppendLine();

        sb.AppendLine($"1. Update connection strings in `src/{spec.ApiProject}/appsettings.json` (or User Secrets).");

        sb.AppendLine($"2. Active connection for Development: **{spec.Setup.ActiveConnectionName}** (`Database:ActiveConnection`).");



        var step = 3;

        if (spec.Entities.Count > 0)

        {

            var scriptsFolder = DatabaseScriptGenerator.ScriptsFolder(spec.Database);

            sb.AppendLine($"{step}. **Database scripts** (in `{scriptsFolder}/`):");

            sb.AppendLine("   - `001-create-tables.sql`");

            sb.AppendLine("   - `002-seed-data.sql` (optional sample data)");

            if (spec.Database == DatabaseProvider.Oracle && !string.IsNullOrWhiteSpace(spec.Setup.OracleSchemaPrefix))

            {

                var example = NamingHelper.ToOracleTableName(spec.Setup.OracleSchemaPrefix, "Lot");

                sb.AppendLine($"   - Oracle table pattern example: `{example}`");

            }

            step++;

        }

        else if (spec.Database == DatabaseProvider.PostgreSql)

        {

            sb.AppendLine($"{step}. **PostgreSQL:** ensure a database exists (e.g. `createdb {spec.ApplicationName}`) or use Docker.");

            step++;

        }



        if (spec.Setup.EnsureCreatedInDevelopment)

        {

            sb.AppendLine($"{step}. **Development:** `EnsureCreated` is enabled — API startup creates tables if missing.");

            sb.AppendLine(spec.Database switch

            {

                DatabaseProvider.Oracle => "   - Production: run SQL scripts in `scripts/oracle/`; do not rely on EnsureCreated.",

                DatabaseProvider.PostgreSql => "   - Production: run SQL scripts in `scripts/postgresql/` or use EF migrations.",

                _ => "   - Production: run SQL scripts in `scripts/sqlserver/` or use EF migrations."

            });

        }



        sb.AppendLine();

        sb.AppendLine("## Run");

        sb.AppendLine();

        sb.AppendLine("```powershell");

        sb.AppendLine($"dotnet build {spec.ApplicationName}.sln");

        if (spec.UiTargets.HasFlag(UiTarget.MvcWeb))

            sb.AppendLine("# VS: \"API + MVC\" profile | Cursor: .vscode \"API + MVC\" compound");

        else

            sb.AppendLine($"dotnet run --project src/{spec.ApiProject}");

        sb.AppendLine("```");

        sb.AppendLine();

        sb.AppendLine("- API Swagger: https://localhost:5001/swagger");

        if (spec.UiTargets.HasFlag(UiTarget.MvcWeb))

            sb.AppendLine("- MVC UI: https://localhost:5101");



        await File.WriteAllTextAsync(Path.Combine(outputDirectory, "README.md"), sb.ToString(), ct);

    }

}


