using System.Text;
using AppGen.Core;
using AppGen.Core.Capabilities;
using AppGen.Core.Models;

namespace AppGen.Engine;

public sealed record ReadmeContext(
    SolutionSpec Spec,
    string OutputDirectory,
    string? OutputRoot = null,
    string? ApiBaseUrl = null,
    bool EnableDocumentation = false,
    bool EnableWeb = false,
    bool EnableMobile = false);

public static class ReadmeGenerator
{
    public static Task WriteAsync(SolutionSpec spec, string outputDirectory, CancellationToken ct = default) =>
        WriteWebAsync(new ReadmeContext(spec, outputDirectory, EnableWeb: true), ct);

    public static async Task WriteHubAsync(ReadmeContext context, CancellationToken ct = default)
    {
        var spec = context.Spec;
        var sb = new StringBuilder();
        sb.AppendLine($"# {spec.ApplicationName}");
        sb.AppendLine();
        AppendAboutSection(sb, spec);
        sb.AppendLine("Generated by AppGen — application factory hub.");
        sb.AppendLine();
        sb.AppendLine("## Manifest");
        sb.AppendLine();
        sb.AppendLine("This folder contains `appgen.json` — the shared application definition (entities, layers, project info).");
        sb.AppendLine();

        if (spec.Entities.Count > 0)
        {
            sb.AppendLine("## Entities");
            sb.AppendLine();
            foreach (var entity in spec.Entities)
                sb.AppendLine($"- **{entity.Name}**");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(context.OutputRoot))
        {
            sb.AppendLine("## Generated layers");
            sb.AppendLine();
            var root = context.OutputRoot.Trim();
            var name = spec.ApplicationName;
            if (context.EnableDocumentation)
                sb.AppendLine($"- [Documentation]({GenerationOutputHelper.GetLayerFolderName(name, ProjectOutputLayer.Documentation)}/README.md) — static portal");
            if (context.EnableWeb)
                sb.AppendLine($"- [Web]({GenerationOutputHelper.GetLayerFolderName(name, ProjectOutputLayer.Web)}/README.md) — API and optional MVC");
            if (context.EnableMobile)
                sb.AppendLine($"- [Mobile]({GenerationOutputHelper.GetLayerFolderName(name, ProjectOutputLayer.Mobile)}/README.md) — Flutter client");
            sb.AppendLine();
        }

        await WriteFileAsync(context.OutputDirectory, sb, ct);
    }

    public static async Task WriteDocumentationAsync(ReadmeContext context, CancellationToken ct = default)
    {
        var spec = context.Spec;
        var password = NamingHelper.NormalizeAppName(spec.ApplicationName).ToLowerInvariant();
        var sb = new StringBuilder();
        sb.AppendLine($"# {spec.ApplicationName} — Documentation");
        sb.AppendLine();
        AppendAboutSection(sb, spec);
        sb.AppendLine("## First run");
        sb.AppendLine();
        sb.AppendLine("1. Open `portal/index.html` in a browser (VS Code **Live Server** recommended).");
        sb.AppendLine("2. If password gate is enabled, default password is the lowercased app name.");
        sb.AppendLine($"   - Example: `{password}`");
        sb.AppendLine("3. Edit content in `portal/data/*.json` or use AppGen **Import from portal folder** to round-trip changes.");
        sb.AppendLine();
        sb.AppendLine("## Troubleshooting");
        sb.AppendLine();
        sb.AppendLine("- **Blank page** — serve via HTTP (Live Server), not `file://`.");
        sb.AppendLine("- **Password not accepted** — check `portal/data/portal-settings.json` or regenerate from AppGen.");
        sb.AppendLine("- **Changes not showing** — hard-refresh the browser or re-import into AppGen manifest.");

        await WriteFileAsync(context.OutputDirectory, sb, ct);
    }

    public static async Task WriteWebAsync(ReadmeContext context, CancellationToken ct = default)
    {
        var spec = context.Spec;
        var sb = new StringBuilder();
        sb.AppendLine($"# {spec.ApplicationName} — Web");
        sb.AppendLine();
        AppendAboutSection(sb, spec);
        sb.AppendLine("Generated by AppGen.");
        sb.AppendLine();
        sb.AppendLine("## First run");
        sb.AppendLine();
        sb.AppendLine($"1. Update connection strings in `src/{spec.ApiProject}/appsettings.json` (or User Secrets).");
        sb.AppendLine($"2. Active connection for Development: **{spec.Setup.ActiveConnectionName}** (`Database:ActiveConnection`).");

        var step = 3;
        if (spec.Entities.Count > 0)
        {
            var scriptsFolder = DatabaseScriptGenerator.ScriptsFolder(spec.Database);
            sb.AppendLine($"{step}. **Database scripts** (in `{scriptsFolder}/`):");
            sb.AppendLine("   - `001-create-tables.sql`");
            sb.AppendLine("   - `002-seed-data.sql` (optional sample data)");
            if (spec.Database == DatabaseProvider.Oracle && !string.IsNullOrWhiteSpace(spec.Setup.OracleSchemaPrefix))
            {
                var example = NamingHelper.ToOracleTableName(spec.Setup.OracleSchemaPrefix, "Lot");
                sb.AppendLine($"   - Oracle table pattern example: `{example}`");
            }
            step++;
        }
        else if (spec.Database == DatabaseProvider.PostgreSql)
        {
            sb.AppendLine($"{step}. **PostgreSQL:** ensure a database exists (e.g. `createdb {spec.ApplicationName}`) or use Docker.");
            step++;
        }

        if (spec.Setup.EnsureCreatedInDevelopment)
        {
            sb.AppendLine($"{step}. **Development:** `EnsureCreated` is enabled — API startup creates tables if missing.");
            sb.AppendLine(spec.Database switch
            {
                DatabaseProvider.Oracle => "   - Production: run SQL scripts in `scripts/oracle/`; do not rely on EnsureCreated.",
                DatabaseProvider.PostgreSql => "   - Production: run SQL scripts in `scripts/postgresql/` or use EF migrations.",
                _ => "   - Production: run SQL scripts in `scripts/sqlserver/` or use EF migrations."
            });
        }

        sb.AppendLine();
        sb.AppendLine("## Run");
        sb.AppendLine();
        sb.AppendLine("```powershell");
        sb.AppendLine($"dotnet build {spec.ApplicationName}.sln");
        sb.AppendLine($"dotnet test {spec.ApplicationName}.sln");
        if (TargetFlags.AuthEnabled(spec))
        {
            sb.AppendLine();
            sb.AppendLine("## Authentication");
            sb.AppendLine();
            sb.AppendLine("- JWT auth is enabled on entity API controllers.");
            sb.AppendLine("- Dev user: `dev@appgen.local` / `AppGen123!` (seeded in Development and test runs).");
            sb.AppendLine("- Set `Jwt:Key` via User Secrets for non-development environments.");
        }
        if (spec.UiTargets.HasFlag(UiTarget.MvcWeb))
            sb.AppendLine("# VS: \"API + MVC\" profile | Cursor: .vscode \"API + MVC\" compound");
        else
            sb.AppendLine($"dotnet run --project src/{spec.ApiProject}");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("- API Swagger: https://localhost:5001/swagger");
        if (spec.UiTargets.HasFlag(UiTarget.MvcWeb))
            sb.AppendLine("- MVC UI: https://localhost:5101");

        sb.AppendLine();
        sb.AppendLine("## Troubleshooting");
        sb.AppendLine();
        sb.AppendLine("- **Database connection failed** — verify connection string name matches `Database:ActiveConnection`.");
        sb.AppendLine("- **Port already in use** — change URLs in `launchSettings.json` or stop the conflicting process.");
        sb.AppendLine("- **Tables missing in production** — run SQL scripts; do not rely on `EnsureCreated` outside Development.");
        sb.AppendLine("- **Mobile client cannot connect** — ensure API is running and CORS allows the client origin.");

        await WriteFileAsync(context.OutputDirectory, sb, ct);
    }

    public static async Task WriteMobileAsync(ReadmeContext context, CancellationToken ct = default)
    {
        var spec = context.Spec;
        var apiBaseUrl = context.ApiBaseUrl
            ?? spec.Targets?.Mobile.ApiBaseUrl
            ?? "https://localhost:5001";
        var sb = new StringBuilder();
        sb.AppendLine($"# {spec.ApplicationName} — Mobile");
        sb.AppendLine();
        AppendAboutSection(sb, spec);
        sb.AppendLine("Flutter proof-of-concept generated by AppGen.");
        sb.AppendLine();
        sb.AppendLine("## Prerequisites");
        sb.AppendLine();
        sb.AppendLine("- [Flutter SDK](https://docs.flutter.dev/get-started/install) (`flutter doctor`)");
        sb.AppendLine("- **Web API must be running** before the mobile app can load data (see Web layer README).");
        sb.AppendLine();
        sb.AppendLine("## First run");
        sb.AppendLine();
        sb.AppendLine("```powershell");
        sb.AppendLine("flutter pub get");
        sb.AppendLine("flutter run");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine($"API base URL in generated config: `{apiBaseUrl}`");
        if (TargetFlags.AuthEnabled(spec))
        {
            sb.AppendLine();
            sb.AppendLine("## Authentication");
            sb.AppendLine();
            sb.AppendLine("- Login screen is shown when Web JWT auth is enabled.");
            sb.AppendLine("- Dev credentials: `dev@appgen.local` / `AppGen123!`");
        }
        if (TargetFlags.OfflineEnabled(spec))
        {
            sb.AppendLine();
            sb.AppendLine("## Offline cache");
            sb.AppendLine();
            sb.AppendLine("- SQLite cache stores entity list responses for offline reading.");
            sb.AppendLine("- Does not require login when Web auth is disabled.");
        }

        var capabilities = MobileCapabilityResolver.Resolve(spec)
            .Where(c => c.IsImplemented && c.Id is not (
                MobileCapabilityId.OfflineCache
                or MobileCapabilityId.SecureStorage
                or MobileCapabilityId.JwtAuth))
            .ToList();
        if (capabilities.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Capabilities");
            sb.AppendLine();
            foreach (var cap in capabilities)
                sb.AppendLine($"- **{cap.DisplayName}** (`{cap.Id}`) — see `lib/core/services/`");
            sb.AppendLine();
            sb.AppendLine("Platform permissions are merged into Android/iOS project files when Flutter platforms are scaffolded.");
            if (capabilities.Any(c => c.Id == MobileCapabilityId.Maps))
            {
                sb.AppendLine();
                sb.AppendLine("**Maps:** configure a Google Maps API key in `android/app/src/main/AndroidManifest.xml` and iOS `AppDelegate` per [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) docs.");
            }
        }

        sb.AppendLine();
        sb.AppendLine("## Troubleshooting");
        sb.AppendLine();
        sb.AppendLine("- **Connection refused** — start the Web API first; confirm `apiBaseUrl` matches Swagger.");
        sb.AppendLine("- **Android emulator** — use `http://10.0.2.2:<port>` instead of `localhost` for the host machine.");
        sb.AppendLine("- **HTTPS / certificate errors** — use HTTP in development or trust the dev certificate.");
        sb.AppendLine("- **Empty list** — verify the entity exists in the API and returns data from Swagger.");
        sb.AppendLine("- **CORS errors** — enable CORS on the API for the Flutter debug origin.");

        await WriteFileAsync(context.OutputDirectory, sb, ct);
    }

    private static void AppendAboutSection(StringBuilder sb, SolutionSpec spec)
    {
        if (spec.Project is null)
            return;

        if (!string.IsNullOrWhiteSpace(spec.Project.Tagline))
        {
            sb.AppendLine($"*{spec.Project.Tagline.Trim()}*");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(spec.Project.Description))
        {
            sb.AppendLine("## About");
            sb.AppendLine();
            sb.AppendLine(spec.Project.Description.Trim());
            sb.AppendLine();
        }
    }

    private static async Task WriteFileAsync(string outputDirectory, StringBuilder sb, CancellationToken ct)
    {
        Directory.CreateDirectory(outputDirectory);
        await File.WriteAllTextAsync(Path.Combine(outputDirectory, "README.md"), sb.ToString(), ct);
    }
}
