using System.Text;
using AppGen.Core.Models;

namespace AppGen.Engine;

public static class SqlServerScriptGenerator
{
    public static async Task WriteAsync(SolutionSpec spec, string outputDirectory, CancellationToken ct = default)
    {
        if (spec.Database != DatabaseProvider.SqlServer || spec.Entities.Count == 0)
            return;

        var scriptDir = Path.Combine(outputDirectory, "scripts", "sqlserver");
        Directory.CreateDirectory(scriptDir);

        await File.WriteAllTextAsync(
            Path.Combine(scriptDir, "001-create-tables.sql"),
            BuildCreateScript(spec),
            ct);

        await File.WriteAllTextAsync(
            Path.Combine(scriptDir, "002-seed-data.sql"),
            BuildSeedScript(spec),
            ct);
    }

    private static string BuildCreateScript(SolutionSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by AppGen. Run against your SQL Server database before or instead of EnsureCreated.");
        sb.AppendLine();

        foreach (var entity in spec.Entities)
        {
            var table = QualifiedTable(entity, spec.Database);
            var props = EntityGenerator.ExpandEntityProperties(entity);

            sb.AppendLine($"-- {entity.Name}");
            sb.AppendLine($"CREATE TABLE {table} (");
            var columns = props.Select(p =>
                $"    {Bracket(ColumnName(p))} {MapType(p)}{(p.IsNullable ? " NULL" : " NOT NULL")}");
            sb.AppendLine(string.Join($",{Environment.NewLine}", columns));

            var key = props.First(p => p.IsKey);
            sb.AppendLine($",    CONSTRAINT {Bracket($"PK_{SqlScriptHelpers.TableName(entity)}")} PRIMARY KEY ({Bracket(ColumnName(key))})");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        foreach (var entity in spec.Entities)
        {
            foreach (var prop in EntityGenerator.ExpandEntityProperties(entity).Where(p => !p.IsKey))
            {
                var refEntity = SqlScriptHelpers.ResolveForeignKeyEntity(spec, prop);
                if (refEntity is null) continue;

                var tableOnly = SqlScriptHelpers.TableName(entity);
                var refTable = SqlScriptHelpers.TableName(refEntity);
                var refKey = EntityGenerator.ExpandEntityProperties(refEntity).First(p => p.IsKey);
                sb.AppendLine($"ALTER TABLE {QualifiedTable(entity, spec.Database)}");
                sb.AppendLine($"    ADD CONSTRAINT {Bracket($"FK_{tableOnly}_{ColumnName(prop)}")}");
                sb.AppendLine($"    FOREIGN KEY ({Bracket(ColumnName(prop))}) REFERENCES {QualifiedTable(refEntity, spec.Database)} ({Bracket(ColumnName(refKey))});");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string BuildSeedScript(SolutionSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Simple sample data. Adjust or re-run after clearing tables.");
        sb.AppendLine();

        var entitySeedIds = SeedScriptHelpers.AssignEntitySeedIds(spec);
        foreach (var entity in spec.Entities)
        {
            var table = QualifiedTable(entity, spec.Database);
            var props = EntityGenerator.ExpandEntityProperties(entity);
            var columns = string.Join(", ", props.Select(p => Bracket(ColumnName(p))));
            var values = string.Join(", ", props.Select(p => SampleValue(entity, p, spec, entitySeedIds)));
            sb.AppendLine($"INSERT INTO {table} ({columns}) VALUES ({values});");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string QualifiedTable(EntitySpec entity, DatabaseProvider database) =>
        $"{Bracket(SqlScriptHelpers.SchemaOrDefault(entity, database))}.{Bracket(SqlScriptHelpers.TableName(entity))}";

    private static string ColumnName(PropertySpec p) =>
        SqlScriptHelpers.ColumnName(p, DatabaseProvider.SqlServer);

    private static string Bracket(string identifier) => $"[{identifier.Replace("]", "]]", StringComparison.Ordinal)}]";

    private static string MapType(PropertySpec p) => p.ClrType switch
    {
        "string" => "NVARCHAR(MAX)",
        "int" => "INT",
        "long" => "BIGINT",
        "decimal" => "DECIMAL(18,4)",
        "double" => "FLOAT",
        "bool" => "BIT",
        "DateTime" => "DATETIME2",
        "Guid" => "UNIQUEIDENTIFIER",
        _ => "NVARCHAR(MAX)"
    };

    private static string SampleValue(
        EntitySpec entity,
        PropertySpec p,
        SolutionSpec spec,
        IReadOnlyDictionary<string, long> entitySeedIds)
    {
        if (p.IsKey)
            return SeedScriptHelpers.KeySampleValue(entity, entitySeedIds);

        var fkValue = SeedScriptHelpers.ForeignKeySampleValue(spec, p, entitySeedIds);
        if (fkValue is not null)
            return fkValue;

        return p.ClrType switch
        {
            "string" => $"N'Sample {p.Name.Replace("'", "''", StringComparison.Ordinal)}'",
            "int" => "1",
            "long" => "1",
            "decimal" or "double" => "0",
            "bool" => "0",
            "DateTime" => "SYSUTCDATETIME()",
            "Guid" => "NEWID()",
            _ => "NULL"
        };
    }
}
